@startuml
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor Dokter
actor Perawat
actor Admin

rectangle "MediChart EMR" {
  usecase "Login" as UC_Login
  usecase "Lihat Dashboard" as UC_Dashboard

  usecase "Lihat Daftar Pasien" as UC_List
  usecase "Cari Data Pasien" as UC_Search
  usecase "Tambah Pasien Baru" as UC_AddPatient
  usecase "Edit Data Pasien" as UC_EditPatient
  usecase "Lihat Data Demographics" as UC_Demographics

  usecase "Lihat Riwayat SOAP" as UC_SoapHistory
  usecase "Input Keluhan Pasien" as UC_Complaint
  usecase "Input Diagnosa\nProblem List" as UC_ProblemList
  usecase "Input Catatan Klinis\nSOAP" as UC_Soap
  usecase "Input Objective /\nTanda Vital" as UC_Objective
  usecase "Simpan Catatan Pemeriksaan" as UC_SaveExam
  usecase "Edit Catatan Pemeriksaan" as UC_EditExam

  usecase "Lihat Diagnostic Reports" as UC_ViewDiag
  usecase "Tambah Laporan Lab" as UC_InputLab
  usecase "Tambah Laporan Radiologi" as UC_InputImaging

  usecase "Kelola Akun Pengguna" as UC_ManageUsers
}

Dokter --> UC_Login
Dokter --> UC_Dashboard
Dokter --> UC_List
Dokter --> UC_Search
Dokter --> UC_AddPatient
Dokter --> UC_EditPatient
Dokter --> UC_Demographics
Dokter --> UC_SoapHistory
Dokter --> UC_Complaint
Dokter --> UC_ProblemList
Dokter --> UC_Soap
Dokter --> UC_SaveExam
Dokter --> UC_EditExam
Dokter --> UC_ViewDiag
Dokter --> UC_InputLab
Dokter --> UC_InputImaging

Perawat --> UC_Login
Perawat --> UC_Dashboard
Perawat --> UC_List
Perawat --> UC_Search
Perawat --> UC_Demographics
Perawat --> UC_SoapHistory
Perawat --> UC_Objective
Perawat --> UC_ViewDiag

Admin --> UC_Login
Admin --> UC_Dashboard
Admin --> UC_ManageUsers

UC_Dashboard ..> UC_List : <<include>>
UC_Search ..> UC_List : <<include>>
UC_AddPatient ..> UC_Demographics : <<include>>

UC_SaveExam ..> UC_Complaint : <<include>>
UC_SaveExam ..> UC_ProblemList : <<include>>
UC_SaveExam ..> UC_Soap : <<include>>

UC_Objective ..> UC_Soap : <<include>>
UC_EditExam ..> UC_Soap : <<include>>

UC_InputLab ..> UC_ViewDiag : <<include>>
UC_InputImaging ..> UC_ViewDiag : <<include>>

@enduml
